matrix:
  - name: Markdown
    aspell:
      lang: en
      d: en_US
    # dictionary:
    #   wordlists:
    #     - .wordlist.txt
    #   encoding: utf-8
    pipeline:
      - pyspelling.filters.context:
          context_visible_first: true
          delimiters:
            - open: '^---$'
              close: '^---$'
      - pyspelling.filters.markdown:
      - pyspelling.filters.html:
          comments: false
          ignores:
            - code
            - pre
    sources:
      - '_posts/*-en.md'
    default_encoding: utf-8
