version: 2.1
orbs:
  node: circleci/node@4.3.0

jobs:
  check:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g markdown-spellcheck
      - run: mdspell "_posts/*-en.md" -r --en-us --ignore-numbers
      - run: [[ $(grep ".moew" **/*.md | grep -Eo "permalink.*" | uniq -cd | wc -l) -eq 0 ]] && echo "ok" || exit 2

workflows:
  spell-check:
    jobs:
      - check
